import type { Metadata } from "next";
import "./globals.css";
import 'normalize.css';
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: "Moonlight Town",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
    <body>
    <main>{children}</main>
    </body>
    </html>
  );
}
