import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'normalize.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moonlight Town",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <header>
        <h1>Moonlight Town</h1>
        <div>
            <button>About me</button>
            <button><a href="https://github.com/andy-thieu/Moonlight-Town/" target="_blank">Github</a></button>
        </div>
    </header>
    <main>{children}</main>
    <footer>
            <p>programmiert von Andy Thieu</p>
            <p><a href="mailto:thieuandyhuy@gmail.com">thieuandyhuy@gmail.com</a></p>
        </footer>
    </body>
    </html>
  );
}
